### ISSUE TITLE
Create documentation for Move2Kube

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube-demos#13]
Create documentation for Move2Kube along the lines of https://kompose.io/

**Comment by ashokponkumar** [comment]
@Akash-Nayak Can you please take it up once the testcase work is done.

**Comment by Akash-Nayak** [comment]
@ashokponkumar Yes sure.

**Comment by ashokponkumar** [comment]
@Akash-Nayak Hope you have got an understanding of how this needs to be done.

**Comment by Akash-Nayak** [comment]
@ashokponkumar Yes, I have got some understanding of how this has to be done. I will create a PR with the first draft of the documentation once it's ready and then we can iterate over it.

**Comment by ashokponkumar** [comment]
Can you please move (close and create new) this issue to the main repo and create more granular tasks for each of the items that need to be done to make the website complete?

**Comment by Akash-Nayak** [comment]
Yes sure, I will do that.
