### ISSUE TITLE
Two services are getting detected in cloud foundry sample with v3 of Move2Kube

### ISSUE THREAD

**Issue by Akash-Nayak** [konveyor/move2kube-demos#48]
**Describe the bug**
```
? Select all services that are needed:
Hints:
[The services unselected here will be ignored.]
  [Use arrows to move, space to select, <right> to all, <left> to none, type to filter]
> [✓]  move2kube-demo-cf
  [✓]  main
 ```

**To Reproduce**
Run Move2Kube v3 over cloud-foundry sample

**Expected behavior**
Detect only one service.

**Comment by ashokponkumar** [comment]
isn't this because of #47 ?

**Comment by Akash-Nayak** [comment]
No, the cloud foundry sample is different. In https://github.com/konveyor/move2kube-demos/pull/47, I have fixed the NodeJS sample inside language-platforms.
